#!/usr/bin/env python3
"""Copy the canonical shared contract into every skill.

shared/*.md        -> skills/<skill>/references/common/
shared/flows/*.md  -> skills/<skill>/references/common/flows/      (v20 flow guides)
shared/generated/* -> skills/<skill>/references/common/generated/  (tables generated by build_adapters.py)
shared/assets/*    -> skills/<skill>/assets/
shared/scripts/*   -> skills/<skill>/scripts/   (e.g. capacity.py)
shared/scoped/...  -> only the skills listed in SCOPED below (one source, a few owners)

Run after editing anything in shared/. `--check` exits 1 if any copy differs (used by validate.py
and CI) without writing anything.
"""
import argparse
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


# A file two skills need (the owner and its fallback when the owner is off in .cecilia/config.json).
# source under shared/scoped/  ->  destinations under skills/
SCOPED = {
    "database/schema-design.md": ["cecilia-db/references/schema-design.md",
                                  "cecilia-design/references/backend/stage-db.md"],
    "database/database-template.md": ["cecilia-db/assets/database.md", "cecilia-design/assets/database.md"],
    "security/threat-model.md": ["cecilia-design/references/security/threat-model.md",
                                 "cecilia-review/references/security/threat-model.md"],
    "security/authz-matrix.md": ["cecilia-design/references/security/authz-matrix.md",
                                 "cecilia-review/references/security/authz-matrix.md"],
    "docs/traceability.md": ["cecilia-design/references/traceability.md",
                             "cecilia-discovery/references/traceability.md"],
    "docs/decision-log.md": ["cecilia-design/references/decision-log.md",
                             "cecilia-discovery/references/decision-log.md"],
    "dev/bugfix.md": ["cecilia-dev-be/references/workflows/bugfix.md", "cecilia-dev-fe/references/workflows/bugfix.md"],
    "dev/refactor.md": ["cecilia-dev-be/references/workflows/refactor.md",
                        "cecilia-dev-fe/references/workflows/refactor.md"],
    "dev/out-of-scope.md": ["cecilia-dev-be/references/workflows/out-of-scope.md",
                            "cecilia-dev-fe/references/workflows/out-of-scope.md"],
    "frontend/visual-check.md": ["cecilia-dev-fe/references/visual-check.md", "cecilia-test/references/visual-check.md"],
    "frontend/image-to-code.md": ["cecilia-dev-fe/references/image-to-code.md"],
    "frontend/web-interface-guidelines.md": ["cecilia-dev-fe/references/web-interface-guidelines.md",
                                             "cecilia-ui/references/web-interface-guidelines.md",
                                             "cecilia-review/references/web-interface-guidelines.md",
                                             "cecilia-test/references/web-interface-guidelines.md"],
    "frontend/uikit.py": ["cecilia-dev-fe/scripts/uikit.py", "cecilia-test/scripts/uikit.py"],
    "frontend/playwright-cli.config.json": ["cecilia-dev-fe/assets/playwright-cli.config.json",
                                            "cecilia-test/assets/playwright-cli.config.json"],
    **{f"frontend/style/{v}.md": [f"cecilia-dev-fe/references/style/{v}.md", f"cecilia-ui/references/style/{v}.md"]
       for v in ("taste", "minimalist", "soft", "brutalist", "redesign")},
    "git/pr-draft-template.md": ["cecilia-dev-be/assets/pr-draft-template.md", "cecilia-dev-fe/assets/pr-draft-template.md",
                                 "cecilia-test/assets/pr-draft-template.md", "cecilia-db/assets/pr-draft-template.md"],
}


SUBDIRS = ("flows", "generated")


def pairs():
    shared = ROOT / "shared"
    for skill in sorted((ROOT / "skills").iterdir()):
        if not skill.is_dir():
            continue
        for src in sorted(shared.glob("*.md")):
            yield src, skill / "references" / "common" / src.name
        for sub in SUBDIRS:
            for src in sorted((shared / sub).glob("*.md")) if (shared / sub).is_dir() else []:
                yield src, skill / "references" / "common" / sub / src.name
        for src in sorted((shared / "assets").glob("*")):
            if src.is_file():
                yield src, skill / "assets" / src.name
    for src in sorted((shared / "scripts").glob("*.py")) if (shared / "scripts").is_dir() else []:
        for skill in sorted((ROOT / "skills").iterdir()):
            if skill.is_dir():
                yield src, skill / "scripts" / src.name
    for src_rel, dests in SCOPED.items():
        for dest in dests:
            if (ROOT / "skills" / dest.split("/")[0]).is_dir():
                yield ROOT / "shared" / "scoped" / src_rel, ROOT / "skills" / dest



def _utf8_console() -> None:
    """Windows consoles default to a legacy code page; keep output readable and crash-free."""
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass

def main() -> int:
    _utf8_console()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report drift, write nothing")
    args = parser.parse_args()
    drift = []
    for src, dst in pairs():
        same = dst.is_file() and dst.read_bytes() == src.read_bytes()
        if same:
            continue
        if args.check:
            drift.append(str(dst.relative_to(ROOT)))
        else:
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(src, dst)
            print("synced", dst.relative_to(ROOT))
    # remove stale common files that no longer exist in shared/
    names = {p.name for p in (ROOT / "shared").glob("*.md")}
    sub_names = {sub: {p.name for p in (ROOT / "shared" / sub).glob("*.md")} for sub in SUBDIRS}
    for common in (ROOT / "skills").glob("*/references/common"):
        for f in [*common.iterdir(), *[g for sub in SUBDIRS if (common / sub).is_dir() for g in (common / sub).iterdir()]]:
            if f.is_dir() and f.name in SUBDIRS and f.parent == common:
                continue
            allowed = sub_names[f.parent.name] if f.parent != common else names
            if f.name not in allowed:
                if args.check:
                    drift.append(str(f.relative_to(ROOT)) + " (stale)")
                else:
                    f.unlink()
                    print("removed stale", f.relative_to(ROOT))
    if drift:
        print("common contract drift:\n  " + "\n  ".join(drift))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
